### ISSUE TITLE
Could not connect to SMTP host:smtp.zts.com.cn:465

### ISSUE THREAD

**Issue by wangfeiily** [looly/looly#1]
邮件发送客户端
Since:
3.2.0
Author:
looly

java应用程序偶发发送邮件报错 Could not connect to SMTP host:smtp.zts.com.cn:465，
但是在该java程序所在机器上运行telnet smtp.zts.com.cn 465 ,显示连接成功。
重启该java程序，发送邮件功能恢复正常。
核心邮件发送模块采用的您 开发的3.2.0 版本。请问你之前有遇到过类似问题么，如何解决的

**Comment by looly** [comment]
这个我忙猜可能是：

1. 连接超时
2. 连接未关闭被服务端拒绝？

一般为网络问题。
